config/routes.rb
Unicorn::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"
  get "myaccount", to: 'myaccount#index'
  get 'myactivities/customise', to: 'my_activities#customise'
  post 'myactivities/transition', to: 'my_activities#transition'
  resources :my_activities, path: 'myactivities', only: [:index, :update], as: 'myactivities'
  resources :activities, only: [:index, :new, :create, :destroy, :edit, :update]
  get "admin", to: 'admin#index'
  scope '/admin' do
    resources :admin_activities, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :admin_users, only: [:index, :edit, :update]
  end

end

app/controllers/admin_activities_controller.rb
class AdminActivitiesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
    @activities = Activity.all.paginate(page: params[:page])
  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.new(activity_params)
    if @activity.save
      flash[:notice] = "New activity created!"
      redirect_to admin_activities_path
    else
       flash[:alert] = "Your new activity contains errors"
     render 'new'
    end
  end

  def destroy
    Activity.find(params[:id]).destroy
    flash[:notice] = "Activity deleted!"
    redirect_to admin_activities_path
  end

  def edit
    @activity = Activity.find_by(id: params[:id])
    if @activity.nil?
      flash[:alert] = "This activity wasn't found"
      redirect_to admin_activities_path
    end
  end

  def update
    @activity = Activity.find_by(id: params[:id])
    if @activity.update_attributes(activity_params)
      flash[:notice] = "Activity successfully updated"
      redirect_to admin_activities_path
    else
      flash[:alert] = "There were errors updating your activity"
      render 'edit'
    end
  end

  private

    def activity_params
      params.require(:activity).permit(:name, :description, :creator_id, :is_public, :is_live)
    end

end

app/helpers/admin_activities_helper.rb
module AdminActivitiesHelper
end

app/views/admin_activities/_activity.html.erb
<tr>
	<td><%= link_to activity.name, edit_admin_activity_path(activity) %></td>
	<td><%= activity.description %></td>
	<td><%= activity.creator_id == nil ? 'Website default' : activity.creator_id %></td>
	<td><%= activity.is_public %></td>
	<td><%= activity.is_live %></td>
	<td><%= link_to "delete", admin_activity_path(activity.id), data: { method: :delete, confirm: "Are you sure?" }, title: "delete" %></td>
</tr>

app/views/admin_activities/edit.html.erb
<% provide(:title, "Edit an activity") %>
<h1>Edit this activity</h1>

<%= simple_form_for @activity, :url => admin_activity_path do |f| %>
	<%= f.input :name, required: true, autofocus: true %>
	<%= f.input :description, required: true %>
	<%= f.input :creator_id, :as => :hidden %>
	<%= f.input :is_public, label: 'Visibility', inline_label: 'Set this activity public',
		hint: "This activity will be displayed to all users if you tick this box" %>
	<%= f.input :is_live, label: 'Status', inline_label: 'Set this activity live',
		hint: "This activity will not be displayed unless you tick this box" %>
	<%= f.button :submit, "Update activity", :class => 'col-xs-offset-3' %>
	<%= link_to "back to activity list", admin_activities_path %>
<% end %>

app/views/admin_activities/index.html.erb
<% provide(:title, "List of all activities") %>
<h1>All activities</h1>
<a href="<%= new_admin_activity_path %>" class="btn btn-primary">Add new activity</a>
<% if @activities.any? %>
	<table class="table">
		<%= render partial: 'admin_activities/activity', collection: @activities %>
	</table>
	<%= will_paginate @activities %>
<% end %>

app/views/admin_activities/new.html.erb
<% provide(:title, 'Create new activity') %>
<h1>Create new activity</h1>

<%= simple_form_for @activity, :url => admin_activities_path  do |f| %>
	<%= f.input :name, required: true, autofocus: true %>
	<%= f.input :description, required: true %>
	<%= f.input :creator_id, :as => :hidden %>
	<%= f.input :is_public, label: 'Visibility', inline_label: 'Set this activity public',
		hint: "This activity will be displayed to all users if you tick this box" %>
	<%= f.input :is_live, label: 'Status', inline_label: 'Set this activity live',
		hint: "This activity will not be displayed unless you tick this box" %>
	<%= f.button :submit, "Create new activity", :class => 'pop col-xs-offset-3' %>
	<%= link_to "back to activity list", admin_activities_path %>
<% end %>