config/routes.rb
Unicorn::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"
  get "myaccount", to: 'myaccount#index'
  get 'myactivities/customise', to: 'my_activities#customise'
  post 'myactivities/transition', to: 'my_activities#transition'
  resources :my_activities, path: 'myactivities', only: [:index, :update], as: 'myactivities'
  resources :activities, only: [:index, :new, :create, :destroy, :edit, :update]
  get "admin", to: 'admin#index'
  scope '/admin' do
    resources :admin_activities, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :admin_users, only: [:index, :edit, :update]
  end

end

app/controllers/my_activities_controller.rb
class MyActivitiesController < ApplicationController
  before_action :logged_in_user

  def index
  	@activities = current_user.user_activities.available
    @started_transition = UserActivity.current_started_transition(current_user)
  end

  def transition
  	activity = current_user.user_activities.find(params[:user_activity_id])
  	activity.state_machine.trigger!(:toggle)
  	@activities = current_user.user_activities.visible
  	respond_to do |format|
  		format.json { render json: @activities }
  	end
  end

  def customise
    @activities = current_user.user_activities.all
  end

  def update
    @activity = UserActivity.find_by(id: params[:id])
    if @activity.update_attributes(user_activity_params)
      respond_to do |format|
        format.json { render json: @activity }
      end
    else
      respond_to do |format|
        format.json { render json: 'error - impossible to update' }
      end
    end
  end

  private

    def user_activity_params
      params.require(:user_activity).permit(:is_displayed)
    end
end

app/helpers/my_activities_helper.rb
module MyActivitiesHelper
end

app/views/my_activities/_activity.html.erb
<div class="col-md-3 col-sm-4 col-xs-6">
	<button class="btn btn-lg col-xs-12 user-activity user-activity-<%= activity.state %>" data-role="transition-user-activity" data-id="<%= activity.id %>" data-state="<%= activity.state_machine.current_state %>" data-url="<%= myactivities_transition_path %>" data-toggle="tooltip" data-placement= "top" title="<%= activity.activity.description %>">
		<%= activity.activity.name %>
	</button>
</div>

app/views/my_activities/_activity_customisable.html.erb
<div class="col-md-3 col-sm-4 col-xs-6">
	<button class="btn btn-lg col-xs-12 user-activity" data-role="change-display-user-activity" data-id="<%= activity_customisable.id %>" data-value="<%= activity_customisable.is_displayed %>" data-url="<%= myactivity_path(activity_customisable) %>">
		<%= activity_customisable.activity.name %>
		<span class="badge pull-right state-<%= activity_customisable.is_displayed ? 'on' : 'off' %>" data-role="action-tag"><%= activity_customisable.is_displayed ? 'on' : 'off' %></span>
	</button>
</div>

app/views/my_activities/customise.html.erb
<% provide(:title, 'Customise your activities') %>
<h1>
	Customise your activities
	<span class="controls"><%=link_to "back to tracking", myactivities_path %></span>
</h1>

<h2>Toggle to change which activities are displayed</h2>
<%= render partial: 'my_activities/activity_customisable', collection: @activities %>

app/views/my_activities/index.html.erb
<% provide(:title, "My activities") %>
<h1>
	My Activities
	<span class="controls"><%=link_to "customise your activities", myactivities_customise_path %></span>
</h1>
<p class="error"></p>
<div id="activity-start-time" data-date="<%= @started_transition.nil? ? DateTime.now : @started_transition.created_at %>" data-action="<%= @started_transition.nil? ? 'stop' : 'start' %>"></div>
<%= form_tag(controller: 'my_activities', action: 'transition') %>
<%= render partial: 'my_activities/activity', collection: @activities %>