config/routes.rb
Unicorn::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root "static_pages#home"
  get "myaccount", to: 'myaccount#index'
  get 'myactivities/customise', to: 'my_activities#customise'
  post 'myactivities/transition', to: 'my_activities#transition'
  resources :my_activities, path: 'myactivities', only: [:index, :update], as: 'myactivities'
  resources :activities, only: [:index, :new, :create, :destroy, :edit, :update]
  get "admin", to: 'admin#index'
  scope '/admin' do
    resources :admin_activities, only: [:index, :new, :create, :destroy, :edit, :update]
    resources :admin_users, only: [:index, :edit, :update]
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	after_initialize :default_values
	validates :name, presence: true, length: { maximum: 20 }
	validates :description, presence: true, length: { maximum: 100 }
	has_many :user_activities, dependent: :destroy
	scope :visible_to_all, -> { where(is_public: true, is_live: true) }

	def default_values
		self.is_public = true if self.is_public.nil?
		self.is_live = true if self.is_live.nil?
	end

	def self.available_activities(user)
		Activity.where(creator_id: [nil, user.id], is_public: true, is_live: true)
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:google_oauth2]
  
  has_many :user_activities, dependent: :destroy
  has_many :activities, through: :user_activities, foreign_key: "creator_id", dependent: :destroy
  
  after_create :generate_default_activities
  after_create :send_welcome_email

  def generate_default_activities
  	UserActivity.generate_initial_activities(self)
  end

  def send_welcome_email
    UserMailer.welcome_email(self).deliver
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:email => data["email"]).first
    unless user
      user = User.create(email: data["email"],
        password: Devise.friendly_token[0,20],
        provider: access_token.provider,
        uid: access_token.uid,
      )
    end
    user
  end
end

app/models/user_activity.rb
class UserActivity < ActiveRecord::Base
  include Statesman::Adapters::ActiveRecordQueries

  belongs_to :user
  belongs_to :activity
  has_many :user_activity_transitions
  validates :user_id, presence: true
  validates :activity_id, presence: true
  scope :visible,  -> { where(is_displayed: true) }

  def self.available
    visible.joins(:activity).merge(Activity.visible_to_all)
  end

  def self.generate_initial_activities(user)
  	@activities = Activity.available_activities(user)
    UserActivity.transaction do
  		@activities.each do |activity|
        UserActivity.create(activity: activity, user: user, is_displayed: true)
  		end
  	end
  end

  # Initialize the state machine
  def state_machine
    @state_machine ||= UserActivityStateMachine.new(self, transition_class: UserActivityTransition)
  end

  # Return the current started activity for that user, or nil
  def self.current_started_transition(user)
    started_activity = user.user_activities.in_state(:started)
    started_activity.empty? ? nil : self.find(started_activity).state_machine.last_transition
  end

  private

    def self.transition_class
      UserActivityTransition
    end

    def self.initial_state
      UserActivityStateMachine.initial_state
    end
end

app/models/user_activity_state_machine.rb
class UserActivityStateMachine
	include Statesman::Machine

	#saving the current state in the UserActivity model
	after_transition do |model, transition|
		model.state = transition.to_state
		model.save!
	end

	#Define all possible states
	state :stopped, initial: :true
	state :started

	#Define transition rules
	transition from: :stopped, to: :started
	transition from: :started, to: :stopped

	#If a user activity starts, stops all other that were already started for that user
	before_transition(from: :stopped, to: :started) do |user_activity, transition|
		user_activity.user.user_activities.in_state(:started).readonly(false).each do |act|
			act.state_machine.transition_to!(:stopped)
		end
	end

	event :toggle do
		transition from: :started, to: :stopped
		transition from: :stopped, to: :started
	end
end

app/models/user_activity_transition.rb
class UserActivityTransition < ActiveRecord::Base
  include Statesman::Adapters::ActiveRecordTransition
  
  belongs_to :user_activity, inverse_of: :user_activity_transitions
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :logged_in_user

  def index
  end

  def new
  end

  def create
  end

  def destroy
  end

  def edit
  end

  def update
  end

  private

    def activity_params
      params.require(:activity).permit(:name, :description, :creator_id, :is_public, :is_live)
    end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  
  def index
  end
end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
  	@users = User.all.paginate(page: params[:page])
  end

  def edit
  	@user = User.find_by(id: params[:id])
    if @user.nil?
      flash[:alert] = "This user wasn't found"
      redirect_to admin_users_path
    end
  end

  def update
  	@user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:notice] = "User successfully updated"
      redirect_to admin_users_path
    else
      flash[:alert] = "There were errors updating this user"
      render 'edit'
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :admin)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include UsersHelper
end

app/controllers/myaccount_controller.rb
class MyaccountController < ApplicationController
  before_action :logged_in_user

  def index
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/admin_activities_helper.rb
module AdminActivitiesHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_activities_helper.rb
module MyActivitiesHelper
end

app/helpers/myaccount_helper.rb
module MyaccountHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def logged_in_user
		redirect_to new_user_session_path, notice: "Please notice first" unless current_user
	end

	def admin_user
		redirect_to root_path, notice: "Unauthorised access" unless current_user && current_user.admin
	end

	def admin_user?
		current_user ? current_user.admin : false
	end
end

app/views/admin/index.html.erb
<% provide(title: 'Admin section') %>
<h1>Admin centre</h1>

<table class="table">
	<tr>
		<td>There are <%= Activity.count %> activities</td>
		<td><%= link_to "Manage activities", admin_activities_path, :class => 'btn btn-primary' %></td>
	</tr>
	<tr>
		<td>There are <%= User.count %> users</td>
		<td><%= link_to "Manage users", admin_users_path, :class => 'btn btn-primary' %></td>
	</tr>
</table>

app/views/layouts/_alerts.html.erb
<% if notice %>
	<div class="alert alert-success alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">close</span>
    </button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert">
      <span aria-hidden="true">&times;</span>
      <span class="sr-only">close</span>
    </button>
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="site-navbar">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#top-navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo.png", size: "88x50", alt: 'Unicorn App'), root_path, :class => "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="top-navbar">
      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>
      		<% if admin_user? %>
  	        	<li><%= link_to "Admin", admin_path %></li>
      		<% end %>
            <li><%= link_to "My activities", myactivities_path %></li>
            <li><%= link_to "My account", myaccount_path %></li>
  	        <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
  	    <% else %>
  	        <li class="list-button"><%= link_to "Log in", new_user_session_path, :class => 'btn pop' %></li>
  	        <li><%= link_to "Sign up", new_user_registration_path %></li>
  	    <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Unicorn | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body id= "page-top" class="index">

<%= render 'layouts/header' %>

<div class="container">
  <%= render 'layouts/alerts' %>
	<%= yield %>
	<%= debug(params) if Rails.env.development? %>
</div>

</body>
</html>